version: "3.8"

services:
  frontend:
    container_name: dockerwebsite_frontend_1
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./webapp/build:/usr/share/nginx/html
    networks:
      - dockerwebsite_app-network

  backend:
    container_name: dockerwebsite_backend_1
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - database
    networks:
      - dockerwebsite_app-network

  database:
    container_name: dockerwebsite_database_1
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - dockerwebsite_app-network

  nginx:
    container_name: dockerwebsite_nginx_1
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - dockerwebsite_app-network

networks:
  dockerwebsite_app-network:
    driver: bridge

volumes:
  dbdata:
